const data = [
    {
        id: 1,
        views: 8,
        updated: '',
        title: 'Hot & Sour Shrimp Soup',
        subtitle: 'This is a simple yet delicious creamy tom yum soup: a Thai hot and sour soup that is aromatic, rich, spicy, and satisfying! Plus, this recipe is customizable, meat-free, and can be made vegan!',
        prep: "Add the shrimp stock, lemongrass, kaffir lime leaves, galangal and chilies to the pot.  Bring to a boil and let it boil for 3-4 minutes until you can smell the fragrance of the herbs from the pot. When the soup is done simmering, add the oyster mushrooms, and bring the soup back to a boil. Once the soup comes back to a boil, add the shrimp and when the soup just starts to bubble again, turn off the heat. Let the residual heat of the soup cook the shrimp completely, another minute or so. Add the lime juice, fish sauce, chili paste (if using) and sugar to your soup and stir. Taste and adjust seasoning to your liking. If you’re not using the chili paste, you may find you need to add a bit more fish sauce/sugar. But taste it first! Garnish with cilantro leaves and serve with rice or turn it into a “Kuay Tiew Tom Yum” by pouring the soup over rice noodles for a pho-style meal!",
        ingredients: ['4 cups shrimp stock (see recipe), chicken stock, or water',
        '8–12 medium sized shrimp, head and shell on if possible',
        '5–6 kaffir lime leaves, roughly torn or cut',
        '1 lemongrass stalk, smashed and cut into 1-2 inch pieces',
        '7–8 rounds galangal, thinly sliced',
        'Thai chilies, to taste, bruised and cut into large pieces',
        '3–4 Tbsp Thai chilli paste, optional',
        '1/2 cup lime juice',
        '3 Tbsp fish sauce',
        '1–2 tsp sugar',
        '3 cups oyster mushroom, cut or tear large ones into bite-sized pieces',
        'Cilantro for  garnish'],
        image: '/images/tomyumgoong.jpg'
                
    },
    {
        id: 2,
        views: 5,
        updated: '',
        title: 'Stir-Fried Noodles',
        subtitle: 'This is a Pad Thai recipe that truly stacks up to great Thai restaurants yet is totally doable for every home cook with just a trip to your every day grocery store.',
        prep: "Place noodles in a large bowl, pour over plenty of boiling water. Soak for 5 minutes, then drain in a colander and quickly rinse under cold water. Don't leave them sitting around for more than 5 - 10 minutes. Mix Sauce in small bowl. Heat 2 tbsp oil in a large non stick pan (or well seasoned skillet) over high heat. Add garlic and onion, cook for 30 seconds. Add chicken and cook for 1 1/2 minutes until mostly cooked through. Push to one side of the pan, pour egg in on the other side. Scramble using the wooden spoon (add touch of extra oil if pan is too dry), then mix into chicken. Add bean sprouts, tofu, noodles then Sauce. Toss gently for about 1 1/2 minutes until Sauce is absorbed by the noodles. Add garlic chives and half the peanuts. Toss through quickly then remove from heat. Serve immediately, sprinkled with remaining peanuts and lime wedges on the side, with a sprinkle of chilli and a handful of extra beansprouts on the side if desired (this is the Thai way!). Squeeze over lime juice to taste before eating.",
        ingredients:['125 g / 4oz Pad Thai dried rice sticks',
        '1 1/2 tbsp tamarind puree',
        '3 tbsp (packed) brown sugar',
        '2 tbsp fish sauce',
        '1 1/2 tbsp oyster sauce',
        '2 - 3 tbsp vegetable or canola oil',
        '1/2 onion , sliced (brown, yellow)',
        '2 garlic cloves , finely chopped',
        '150 g/5oz chicken breast (or thigh) , thinly sliced',
        '2 eggs , lightly whisked',
        '1 1/2 cups of beansprouts',
        '1/2 cup firm tofu, cut into 3cm / 1 1/4" batons',
        '1/4 cup garlic chives , cut into 3cm / 1 1/4" pieces',
        '1/4 cup finely chopped peanuts'],
        image: '/images/padthai.jpg'
        
    },
    {
        id: 3,
        views: 10,
        updated: '',
        title: 'Green Chicken Curry',
        subtitle: 'For the spiciest curry you can get, look no further than the gaeng keow wan gai!',
        prep: "Put 225g new potatoes, cut into chunks, in a pan of boiling water and cook for 5 minutes. Add 100g trimmed and halved green beans and cook for a further 3 minutes, by which time both should be just tender but not too soft. Drain and put to one side. In a wok or large frying pan, heat 1 tbsp vegetable or sunflower oil until very hot, then drop in 1 chopped garlic clove and cook until golden, this should take only a few seconds. Don’t let it go very dark or it will spoil the taste. Spoon in 1 rounded tbsp Thai green curry paste and stir it around for a few seconds to begin to cook the spices and release all the flavours. Next, pour in a 400ml can of coconut milk and let it come to a bubble. Stir in 2 tsp Thai fish sauce and 1 tsp caster sugar, then 450g bite-size chicken pieces. Turn the heat down to a simmer and cook, covered, for about 8 minutes until the chicken is cooked. Tip in the potatoes and beans and let them warm through in the hot coconut milk, then add 2 finely shredded kaffir lime leaves (or 3 wide strips lime zest). Add a good handful basil leaves, but only leave them briefly on the heat or they will quickly lose their brightness. Scatter with lime to garnish and serve immediately with boiled rice.",
        ingredients:['225g new potatoes, cut into chunks',
        '100g green beans, trimmed and halved',
        '1 tbsp vegetable or sunflower oil',
        '1 garlic clove, chopped',
        '1 rounded tbsp or 4 tsp Thai green curry paste',
        '400ml can coconut milk',
        '2 tsp Thai fish sauce',
        '1 tsp caster sugar',
        '450g boneless skinless chicken (breasts or thighs), cut into bite-size pieces',
        '2 fresh kaffir lime leaves finely shredded, or 3 wide strips lime zest, plus extra to garnish',
        'good handful of basil leaves'],
        image: '/images/greenchickencurry.jpg'
    },
    {
        id: 4,
        views: 13,
        updated: '',
        title: 'Red Curry',
        subtitle: "Forget ordering takeaway and make your own Thai red curry at home. This classic dish takes just 15 minutes to prep and it's bursting with flavour.",
        prep: "Heat 1 tbsp vegetable oil in a large saucepan over a medium heat and fry 1 tbsp ginger and 1 tbsp garlic paste for 2 mins. Add 5-6 tbsp red curry paste, sizzle for a few secs, then pour in 800ml coconut milk. Bring to the boil, reduce to a simmer, stir a little and wait for the oil to rise to the surface. Add 8 skinless, boneless chicken thighs, cut into chunks, and kaffir lime leaves, and simmer for 12 mins or until the chicken is cooked through. Add 1 tbsp of the fish sauce and a pinch of brown sugar, then taste – if you like it a little saltier, add more fish sauce; if you like it sweeter, add a little more sugar. Bring to the boil, take off the heat and add ½ small pack Thai basil. Spoon the curry into four bowls and top with 1 red chilli, a thumb-sized piece of ginger and a few extra basil leaves. Serve with jasmine rice.",
        ingredients:['1 tbsp vegetable oil',
        '1 tbsp ginger & garlic paste',
        '5-6 tbsp red curry paste',
        '800ml coconut milk',
        '8 skinless, boneless chicken thighs, cut into large chunks',
        'kaffir lime leaves (ideally fresh)',
        '2 tbsp fish sauce',
        '1 tsp brown sugar',
        '½ small pack Thai basil',
        'basil or coriander, plus extra to serve',
        '1 red chilli, sliced diagonally',
        'thumb-sized piece ginger, cut into matchsticks'],
        image: '/images/redcurry.jpg'         
    },
    {
        id: 5,
        views: 23,
        updated: '',
        title: 'Fried Rice',
        subtitle: 'This is a very famous rice dish of Thailand which is flavoured with herbs and spices. The herbs along with egg, chicken and drizzle of lemon juice makes it an exotic platter to enjoy.',
        prep: "Wash and pat dry chicken. Add soya sauce and cornflour in chicken and keep aside for 10 minutes. Fry eggs into pieces. Heat oil in a pan. Add chopped garlic and saute 3 minutes. Now add the chicken pieces and stir for 10 minutes. Add onion and chilli pepper. Add tomato, spring onion and eggs. In a different pan add fish sauce, Thai pepper powder, salt, sugar, lime juice and cooked rice. Mix them together. Add vegetable and chicken in rice. Again mix until all ingredients are well combined. Serve with lemon wedges and cucumber slices.",
        ingredients:['1½ cup Jasmine rice cooked',
        '400 grams Chicken boneless cut into small pieces',
        '1 table spoon Corn flour',
        '2 eggs beaten',
        '1 tbsp Finely chopped garlic',
        '1/2 cup Onion slice half cup',
        '5 table spoon Oil',
        '1/4 cup thai chilli pepper',
        '1/2 tsp thai pepper powder',
        '2 tbsp fish sauce',
        '1 tbsp soy sauce',
        'to taste Salt',
        '1 tbsp Lime juice',
        '1 tsp Sugar',
        '1 Tomato chopped',
        'as required Spring onion chopped',
        'handful Coriander leaves for garnishing'],
        image: '/images/khaopad.jpg'          
    },
    {
        id: 6,
        views: 11,
        updated: '',
        title: 'Chicken in Coconut Soup',
        subtitle: 'This Tom Kha soup recipe (or Thai coconut chicken soup) is absolutely perfect. Rich and creamy yet tangy and salty, this Thai coconut chicken soup recipe is filling but light and positively bursting with flavor.',
        prep: "Using the back of a knife, lightly smash lemongrass and ginger; cut lemongrass into 4” pieces. Bring lemongrass, ginger, lime leaves, and broth to a boil in a large saucepan. Reduce heat and simmer until flavors are melded, 8–10 minutes. Strain broth into clean saucepan; discard solids. Add chicken and return to a boil. Reduce heat, add mushrooms, and simmer, skimming occasionally, until chicken is cooked through and mushrooms are soft, 20–25 minutes. Mix in coconut milk, fish sauce, and sugar. Divide soup among bowls. Serve with chili oil, cilantro, and lime wedges.",
        ingredients:['1 Tbsp. coconut oil',
        '1/2 onion sliced',
        '2 garlic cloves chopped',
        '1/2 red jalapeno pepper sliced, or a couple Thai chiles, halved',
        '3 quarter-inch slices slices galangal or ginger',
        '1 lemongrass stalk pounded with the side of a knife and cut into 2-inch long pieces',
        '2 teaspoons red Thai curry paste',
        '4 cups chicken broth see Note 1 if vegan or on Whole30',
        '4 cups canned coconut cream or coconut milk',
        '2 medium chicken breasts cut into bite-sized pieces, see Note 2 for vegan/vegetarian or to use shrimp',
        '8 oz. white mushroom caps sliced',
        '1-2 Tbsp. coconut sugar if on Whole30, see Note 3',
        '1 1/2 - 2 Tbsp. fish sauce plus more to taste, see Note 4 if on Whole30 or vegan',
        '2-3 Tbsp. fresh lime juice',
        '2-3 green onions sliced thin',
        'fresh cilantro chopped, for garnish'],
        image: '/images/tomkhagai.jpg'
    },
    {
        id: 7,
        views: 0,
        updated: '',
        title: 'Creamy Coconut Curry Noodle Soup',
        subtitle: 'Made with such tender shredded chicken in an amazingly fragrant coconut-curry broth that is to die for!',
        prep: "Cook noodles according to package instructions; set aside. Combine coconut milk and red bell peppers in blender until smooth; set aside. Heat canola oil in a large stockpot or Dutch oven over medium heat. Add garlic and shallot, and cook, stirring frequently, until tender, about 3-4 minutes. Stir in red curry paste, ginger and chili powder until fragrant, about 1 minute. Stir in chicken stock and coconut milk mixture, scraping any browned bits from the bottom of the pot. Stir in chicken, fish sauce, soy sauce and brown sugar. Bring to a boil; reduce heat and cook, stirring occasionally, until slightly reduced and chicken is tender, about 15-20 minutes. Remove chicken and shred, using two forks, before returning to the pot; stir in lime juice. Serve immediately with noodles, garnished with red onion, bean sprouts, cilantro and lime, if desired.",
        ingredients:['1 (6-ounce) package chow mein stir-fry noodles',
        '1 (13.5-ounce) can coconut milk',
        '3/4 cup jarred roasted red peppers, drained',
        '1 1/2 tablespoons canola oil',
        '3 cloves garlic, minced',
        '2 shallots, diced',
        '3 tablespoons red curry paste',
        '1 1/2 tablespoons freshly grated ginger',
        '2 teaspoons chili powder',
        '3 cups chicken stock',
        '2 pounds boneless, skinless chicken thighs',
        '1 tablespoon fish sauce',
        '1 tablespoon reduced sodium soy sauce',
        '2 teaspoons brown sugar',
        '2 tablespoons freshly squeezed lime juice',
        '1/2 small red onion, thinly sliced',
        '1/2 cup bean sprouts',
        '1/2 cup cilantro leaves',
        '1 lime, cut in wedges'],
        image: '/images/khaosoi.jpg' 
    },
    {
        id: 8,
        views: 4,
        updated: '',
        title: 'Crispy Catfish with Green Mango Salad',
        subtitle: '',
        prep: "Preheat the oven to 450 degrees F (230 degrees C). Place catfish on a baking sheet. Roast in the preheated oven until flesh is opaque, 10 to 15 minutes. Flake into large pieces with a fork. Lay the flaked fish out on a plate to dry. Heat oil in a large pan over medium-high heat. Fry fish in batches until golden brown, about 5 minutes. Try not to break up the fish too much in the pan. Toss mango, shallots, cilantro, green onions, peanuts, fish sauce, lime juice, Thai chiles, and sugar together in a large bowl. Toss in crispy catfish at the very last minute. Check the seasoning; the salad should taste sour, hot, and salty, with a slight sweetness at the end.",
        ingredients:['1 whole catfish',
        'oil for deep frying',
        '1 cup matchstick-cut green mango pieces',
        '½ cup shallots, thinly sliced',
        '½ cup chopped fresh cilantro',
        '¼ cup chopped green onions',
        '¼ cup peanuts',
        '4 tablespoons fish sauce',
        '2 tablespoons lime juice, or more to taste',
        '3 Thai chiles, finely chopped, or to taste',
        '1 teaspoon white sugar'],
        image: '/images/yumpladukfoo.jpg'
    },
    {
        id: 9,
        views: 18,
        updated: '',
        title: 'Spicy Green Papaya Salad',
        subtitle: "Som tam is a popular Thai salad featuring green papaya and a spicy chili pepper dressing. Traditionally, it's pounded with a mortar and pestle, which can be fun at times. However, it's also messy and a lot of work.",
        prep: "In a small, dry frying pan, toast the peanuts over a medium heat until golden brown. Remove from the pan and set aside. (There’s also a ready-toasted alternative you can find in the supermarkets). Coarsely pound the chillies and garlic together using a pestle and mortar. Add the palm sugar, beans and tomatoes. Lightly pound to combine, then squeeze in the lime juice and fish sauce. Lightly pound again, then add the green papaya and carrot. Pound again and toss to combine. The taste should be sweet and salty in perfect balance, with a sharp, sour and spicy tang. Spoon the salad into a serving bowl and sprinkle over the dried shrimp and toasted peanuts.",
        ingredients:['1 small papaya (green, unripe, firm)',
        '1 clove garlic (minced)',
        '1 red chili pepper (sliced, seeds removed; to taste)',
        '2 tablespoons fish sauce (or soy sauce for vegetarians)',
        '2 tablespoons vegetable oil (light-tasting; not olive oil)',
        '3 tablespoons lime juice',
        '2 tablespoons brown sugar',
        '5 green beans',
        '1 cup cherry tomatoes (cut in half)',
        '2 cups bean sprouts',
        '3 spring onions (sliced into matchstick-like pieces)',
        '1/4 cup fresh basil',
        '1/2 cup peanuts (or cashews, roasted)'],
        image: '/images/somtam.jpg' 
    },
    {
        id: 10,
        views: 4,
        updated: '',
        title: 'Morning Glory',
        subtitle: "This simple yet delicious stir fried vegetable side dish made with Pak Boong (Water Morning Glory; Water Spinach) is one of Thailand's most popular foods.",
        prep: 'Cut the morning glory into 4 inch long pieces and place it in a bowl. Then measure the sauce ingredient and also put those in the bowl. Break up the garlic and chilies and add them to the top of the bowl. Heat the oil in a large wok until very hot, then all at once add the contents of the bowl. Stir and fry quickly, turning for the bottom until the morning glory is wilted. Serve inmediately.',
        ingredients:['1 Bunch Water morning glory, Cut into 4 - 6 inch pieces, about 4 cups',
        '4 Thai Hot Chili',
        '3 large cloves Garlic',
        '1/2 Tablespoon Yellow Soybean Paste',
        '1/2 Tablespoon Light Soy Sauce',
        '1/2 Tablespoon Oyster Sauce',
        '1 Tablespoon Vegetable Oil'],
        image: '/images/padpakboong.jpg'   
    },
    {
        id: 11,
        views: 20,
        updated: '',
        title: 'Drunken Noodles',
        subtitle: 'Drunken Noodles is the literal translation of Pad Kee Mao because the theory is that these spicy Thai noodles should be eaten with an ice cold beer and that they are a great cure for hangover.',
        prep: 'Prepare noodles per packet directions. Mix Sauce in a small bowl. Heat oil in wok or large heavy based skillet over high heat.Add garlic and chilli and cook for 10 seconds. Dont inhale - the chilli will make you cough! Add onion, cook for 1 minute. Add chicken and fish sauce, and fry until cooked, around 2 minutes.Add green onion, noodles and sauce and cook for 1 minute until the sauce reduces and coats the noodles.Remove from heat and immediately add basil, toss until just wilted, then serve immediately.',
        ingredients:['7 oz /200g dried rice noodles , wide',
        '2 tbsp oil (peanut, vegetable or canola)',
        '3 large cloves of garlic , minced',
        '2 birds eye chilli or Thai chillies , deseeded, very finely chopped',
        '1/2 onion , sliced',
        '200 g /7oz chicken thighs , cut into bite size pieces (breast ok too)',
        '2 tsp fish sauce (or soy sauce)',
        '2 green onions , cut into 3cm/2" pieces',
        '1 cup Thai or Thai Holy Basil leaves',
        '3 tbsp oyster sauce',
        '1 1/2 tbsp light soy sauce',
        '1 1/2 tbsp dark soy sauce',
        '2 tsp sugar',
        '1 tbsp water'],
        image: '/images/padkeemao.jpg'   
    },
    {
        id: 12,
        views: 2,
        updated: '',
        title: 'Mango Sticky Rice',
        subtitle: 'End your meals on a sweet note with this lovely treat! Indulge in juicy mango slices and a sticky rice drenched in coconut cream or condensed milk.',
        prep: 'In a bowl wash rice well in several changes of cold water until water is clear. Soak rice in cold water to cover overnight. Drain rice well in a sieve. Set sieve over a large deep saucepan of simmering water (sieve should not touch water) and steam rice, covered with a kitchen towel and a lid, 30 to 40 minutes, or until tender (check water level in pan occasionally, adding more water if necessary). While rice is cooking, in a small saucepan bring 1 cup coconut milk to a boil with 1/3 cup sugar and salt, stirring until sugar is dissolved, and remove from heat. Keep mixture warm. Transfer cooked rice to a bowl and stir in coconut-milk mixture. Let rice stand, covered, 30 minutes, or until coconut-milk mixture is absorbed. Rice may be prepared up to this point 2 hours ahead and kept covered at room temperature. While rice is standing, in cleaned small pan slowly boil remaining 1/3 cup coconut milk with remaining 3 tablespoons sugar, stirring occasionally, 1 minute. Transfer sauce to a small bowl and chill until cool and thickened slightly. To serve, mold 1/4 cup servings of sticky rice on dessert plates. Drizzle desserts with sauce and sprinkle with sesame seeds. Divide mango slices among plates.',
        ingredients:['1 1/2 cups glutinous (sweet) rice',
        '1 1/3 cups well-stirred canned unsweetened coconut milk',
        '1/3 cup plus 3 tablespoons sugar',
        '1/4 teaspoon salt',
        '1 tablespoon sesame seeds, toasted lightly',
        '1 large mango, peeled, pitted, and cut into thin slices (at least 24)'],
        image: '/images/khaoniewmamuang.jpg'   
    }
 
];

export default data;